### ISSUE TITLE
Segfault in spvtools::opt::analysis::Struct::Struct for structs pointing to itself

### ISSUE THREAD

**Issue by karolherbst** [KhronosGroup/SPIRV-Tools#1578]
SPIR-V:

```SPIRV
; SPIR-V
; Version: 1.0
; Generator: Khronos LLVM/SPIR-V Translator; 14
; Bound: 12
; Schema: 0
               OpCapability Addresses
               OpCapability Kernel
          %1 = OpExtInstImport "OpenCL.std"
               OpMemoryModel Physical64 OpenCL
               OpEntryPoint Kernel %7 "test"
               OpSource OpenCL_C 102000
               OpDecorate %11 FuncParamAttr NoCapture
         %11 = OpDecorationGroup
               OpGroupDecorate %11 %8 %9
               OpTypeForwardPointer %_ptr_CrossWorkgroup__struct_3 CrossWorkgroup
       %void = OpTypeVoid
  %_struct_3 = OpTypeStruct %_ptr_CrossWorkgroup__struct_3
%_ptr_CrossWorkgroup__struct_3 = OpTypePointer CrossWorkgroup %_struct_3
%_ptr_CrossWorkgroup__struct_3_0 = OpTypePointer CrossWorkgroup %_struct_3
          %6 = OpTypeFunction %void %_ptr_CrossWorkgroup__struct_3_0 %_ptr_CrossWorkgroup__struct_3_0
          %7 = OpFunction %void Pure %6
          %8 = OpFunctionParameter %_ptr_CrossWorkgroup__struct_3_0
          %9 = OpFunctionParameter %_ptr_CrossWorkgroup__struct_3_0
         %10 = OpLabel
               OpReturn
               OpFunctionEnd
```

ran as gdb --args spirv-opt --skip-validation -O (validation needs to be skipped due to #1577):
```
#0  0x00007ffff7a85db2 in spvtools::opt::analysis::Struct::Struct (this=0x634dc0, types=std::vector of length 1, capacity 1 = {...}) at ../source/opt/types.cpp:412
#1  0x00007ffff7a799bd in spvtools::opt::analysis::TypeManager::RecordIfTypeDefinition (this=0x634b40, inst=...) at ../source/opt/type_manager.cpp:556
#2  0x00007ffff7a7485c in spvtools::opt::analysis::TypeManager::AnalyzeTypes (this=0x634b40, module=...) at ../source/opt/type_manager.cpp:69
#3  0x00007ffff7a745ef in spvtools::opt::analysis::TypeManager::TypeManager(std::function<void (spv_message_level_t, char const*, spv_position_t const&, char const*)> const&, spvtools::ir::IRContext*) (
    this=0x634b40, consumer=..., c=0x632630) at ../source/opt/type_manager.cpp:38
#4  0x00007ffff7924ead in spvtools::ir::IRContext::get_type_mgr (this=0x632630) at ../source/opt/ir_context.h:281
#5  0x00007ffff7a4c5be in spvtools::opt::RemoveDuplicatesPass::AreTypesEqual (inst1=..., inst2=..., context=0x632630) at ../source/opt/remove_duplicates_pass.cpp:197
#6  0x00007ffff7a4c22c in spvtools::opt::RemoveDuplicatesPass::RemoveDuplicateTypes (this=0x62e740, ir_context=0x632630) at ../source/opt/remove_duplicates_pass.cpp:122
#7  0x00007ffff7a4be0b in spvtools::opt::RemoveDuplicatesPass::Process (this=0x62e740, ir_context=0x632630) at ../source/opt/remove_duplicates_pass.cpp:42
#8  0x00007ffff7a36e4e in spvtools::opt::Pass::Run (this=0x62e740, ctx=0x632630) at ../source/opt/pass.cpp:111
#9  0x00007ffff7a3776e in spvtools::opt::PassManager::Run (this=0x62e6e8, context=0x632630) at ../source/opt/pass_manager.cpp:49
#10 0x00007ffff7a20196 in spvtools::Optimizer::Run (this=0x7fffffffda90, original_binary=0x6335f0, original_binary_size=71, optimized_binary=0x7fffffffda70) at ../source/opt/optimizer.cpp:209
#11 0x000000000040f7ce in main (argc=6, argv=0x7fffffffdbe8) at ../tools/opt/opt.cpp:743
```

The cause of this is inside handling of OpTypeStruct in https://github.com/KhronosGroup/SPIRV-Tools/blob/master/source/opt/type_manager.cpp#L551 as element_types contains just NULL, because the type wasn't created yet, just forward declared.

The above SPIR-V can be generated by OpenCL C code like this:
```OpenCL
struct Node {
        global struct Node *node;
};

kernel void test(global struct Node* out, global struct Node* in)
{
}
```

**Comment by s-perron** [comment]
It looks like the current handling of OpTypeForwardPointer does not account for the forward pointer actually being referenced in between the forward declaration and the definition, which is not right.  It will require a redesign.

**Comment by karolherbst** [comment]
thanks a lot!
