### ISSUE TITLE
Tests fail with Python3

### ISSUE THREAD

**Issue by pow2clk** [KhronosGroup/SPIRV-Tools#1645]
When the default python for a system is python3, the ctests involving check_symbol_exports.py produce python errors due to a change in python's willingness to try treating byte data like a string when the programmer asks and hope for the best between python2 and python3:
```

 ctest --output-on-failure --tests-regex spirv-tools-symbol-exports
Test project /home/sadangel/opc/SPIRV-Tools/build
    Start 4: spirv-tools-symbol-exports-SPIRV-Tools
1/4 Test #4: spirv-tools-symbol-exports-SPIRV-Tools ..........***Failed    0.21 sec
Traceback (most recent call last):
  File "/home/sadangel/opc/SPIRV-Tools/utils/check_symbol_exports.py", line 92, in <module>
    main()
  File "/home/sadangel/opc/SPIRV-Tools/utils/check_symbol_exports.py", line 84, in main
    status = check_library(args.library)
  File "/home/sadangel/opc/SPIRV-Tools/utils/check_symbol_exports.py", line 60, in check_library
    for line in command_output(['objdump', '-t', library], '.').split('\n'):
TypeError: a bytes-like object is required, not 'str'

    Start 5: spirv-tools-symbol-exports-SPIRV-Tools-shared
2/4 Test #5: spirv-tools-symbol-exports-SPIRV-Tools-shared ...***Failed    0.09 sec
Traceback (most recent call last):
  File "/home/sadangel/opc/SPIRV-Tools/utils/check_symbol_exports.py", line 92, in <module>
    main()
  File "/home/sadangel/opc/SPIRV-Tools/utils/check_symbol_exports.py", line 84, in main
    status = check_library(args.library)
  File "/home/sadangel/opc/SPIRV-Tools/utils/check_symbol_exports.py", line 60, in check_library
    for line in command_output(['objdump', '-t', library], '.').split('\n'):
TypeError: a bytes-like object is required, not 'str'

    Start 6: spirv-tools-symbol-exports-SPIRV-Tools-opt
3/4 Test #6: spirv-tools-symbol-exports-SPIRV-Tools-opt ......***Failed    0.78 sec
Traceback (most recent call last):
  File "/home/sadangel/opc/SPIRV-Tools/utils/check_symbol_exports.py", line 92, in <module>
    main()
  File "/home/sadangel/opc/SPIRV-Tools/utils/check_symbol_exports.py", line 84, in main
    status = check_library(args.library)
  File "/home/sadangel/opc/SPIRV-Tools/utils/check_symbol_exports.py", line 60, in check_library
    for line in command_output(['objdump', '-t', library], '.').split('\n'):
TypeError: a bytes-like object is required, not 'str'

    Start 7: spirv-tools-symbol-exports-SPIRV-Tools-link
4/4 Test #7: spirv-tools-symbol-exports-SPIRV-Tools-link .....***Failed    0.10 sec
Traceback (most recent call last):
  File "/home/sadangel/opc/SPIRV-Tools/utils/check_symbol_exports.py", line 92, in <module>
    main()
  File "/home/sadangel/opc/SPIRV-Tools/utils/check_symbol_exports.py", line 84, in main
    status = check_library(args.library)
  File "/home/sadangel/opc/SPIRV-Tools/utils/check_symbol_exports.py", line 60, in check_library
    for line in command_output(['objdump', '-t', library], '.').split('\n'):
TypeError: a bytes-like object is required, not 'str'


0% tests passed, 4 tests failed out of 4

Total Test time (real) =   1.19 sec

The following tests FAILED:
	  4 - spirv-tools-symbol-exports-SPIRV-Tools (Failed)
	  5 - spirv-tools-symbol-exports-SPIRV-Tools-shared (Failed)
	  6 - spirv-tools-symbol-exports-SPIRV-Tools-opt (Failed)
	  7 - spirv-tools-symbol-exports-SPIRV-Tools-link (Failed)
Errors while running CTest
```

**Comment by pow2clk** [comment]
I have a fix ready and will have a PR soon.

**Comment by dneto0** [comment]
I'm a Perl programmer at heart.  I'm sure Perl would never break compatibility like this. (Oh wait, I don't know anybody using Perl 6...)  :-)

**Comment by antiagainst** [comment]
I thought Python2 & Python3 are two different languages? ;-P

**Comment by pow2clk** [comment]
@antiagainst pretty close. incompatibilities like this are more common than not 😑
