### ISSUE TITLE
PassManagerTest is leaking an Instruction object

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#2296]
From an ASAN build.

Direct leak of 104 byte(s) in 1 object(s) allocated from:
    #0 0xb341b0 in operator new(unsigned long) (/third_party/spirv-tools/test/opt/test_opt+0xb341b0)
    #1 0x1400f19 in spvtools::opt::Instruction::Clone(spvtools::opt::IRContext*) const /third_party/spirv-tools/source/opt/instruction.cpp:110:24
    #2 0xfe13a0 in spvtools::opt::(anonymous namespace)::DuplicateInstPass::Process() /third_party/spirv-tools/test/opt/pass_manager_test.cpp:110:48
    #3 0x14e49c6 in spvtools::opt::Pass::Run(spvtools::opt::IRContext*) /third_party/spirv-tools/source/opt/pass.cpp:39:25
    #4 0x14e5013 in spvtools::opt::PassManager::Run(spvtools::opt::IRContext*) /third_party/spirv-tools/source/opt/pass_manager.cpp:50:35
    #5 0xfea0c5 in spvtools::opt::PassTest<testing::Test>::RunAndCheck(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /third_party/spirv-tools/test/opt/pass_fixture.h:209:15
    #6 0xfdf2d4 in spvtools::opt::(anonymous namespace)::PassManagerTest_Run_Test::TestBody() /third_party/spirv-tools/test/opt/pass_manager_test.cpp:134:3
    #7 0x1c1abb5 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /third_party/googletest/googletest/src/gtest.cc:2443:10
    #8 0x1be39c7 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /third_party/googletest/googletest/src/gtest.cc:2479:14
    #9 0x1b9d3a8 in testing::Test::Run() /third_party/googletest/googletest/src/gtest.cc:2518:5
    #10 0x1b9f4cd in testing::TestInfo::Run() /third_party/googletest/googletest/src/gtest.cc:2699:11
    #11 0x1ba0610 in testing::TestCase::Run() /third_party/googletest/googletest/src/gtest.cc:2821:28
    #12 0x1bbbca9 in testing::internal::UnitTestImpl::RunAllTests() /third_party/googletest/googletest/src/gtest.cc:5210:43
    #13 0x1c24d50 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /third_party/googletest/googletest/src/gtest.cc:2443:10
    #14 0x1be9757 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /third_party/googletest/googletest/src/gtest.cc:2479:14
    #15 0x1bbb20c in testing::UnitTest::Run() /third_party/googletest/googletest/src/gtest.cc:4818:10
    #16 0x1786750 in RUN_ALL_TESTS() /third_party/googletest/googletest/include/gtest/gtest.h:2456:46
    #17 0x1786692 in main /third_party/googletest/googlemock/src/gmock_main.cc:69:10
    #18 0x7f4902d102b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)

Direct leak of 104 byte(s) in 1 object(s) allocated from:
    #0 0xb341b0 in operator new(unsigned long) (/third_party/spirv-tools/test/opt/test_opt+0xb341b0)
    #1 0x1400f19 in spvtools::opt::Instruction::Clone(spvtools::opt::IRContext*) const /third_party/spirv-tools/source/opt/instruction.cpp:110:24
    #2 0xfe13a0 in spvtools::opt::(anonymous namespace)::DuplicateInstPass::Process() /third_party/spirv-tools/test/opt/pass_manager_test.cpp:110:48
    #3 0x14e49c6 in spvtools::opt::Pass::Run(spvtools::opt::IRContext*) /third_party/spirv-tools/source/opt/pass.cpp:39:25
    #4 0x14e5013 in spvtools::opt::PassManager::Run(spvtools::opt::IRContext*) /third_party/spirv-tools/source/opt/pass_manager.cpp:50:35
    #5 0xfea0c5 in spvtools::opt::PassTest<testing::Test>::RunAndCheck(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /third_party/spirv-tools/test/opt/pass_fixture.h:209:15
    #6 0xfdf140 in spvtools::opt::(anonymous namespace)::PassManagerTest_Run_Test::TestBody() /third_party/spirv-tools/test/opt/pass_manager_test.cpp:129:3
    #7 0x1c1abb5 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /third_party/googletest/googletest/src/gtest.cc:2443:10
    #8 0x1be39c7 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /third_party/googletest/googletest/src/gtest.cc:2479:14
    #9 0x1b9d3a8 in testing::Test::Run() /third_party/googletest/googletest/src/gtest.cc:2518:5
    #10 0x1b9f4cd in testing::TestInfo::Run() /third_party/googletest/googletest/src/gtest.cc:2699:11
    #11 0x1ba0610 in testing::TestCase::Run() /third_party/googletest/googletest/src/gtest.cc:2821:28
    #12 0x1bbbca9 in testing::internal::UnitTestImpl::RunAllTests() /third_party/googletest/googletest/src/gtest.cc:5210:43
    #13 0x1c24d50 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /third_party/googletest/googletest/src/gtest.cc:2443:10
    #14 0x1be9757 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /third_party/googletest/googletest/src/gtest.cc:2479:14
    #15 0x1bbb20c in testing::UnitTest::Run() /third_party/googletest/googletest/src/gtest.cc:4818:10
    #16 0x1786750 in RUN_ALL_TESTS() /third_party/googletest/googletest/include/gtest/gtest.h:2456:46
    #17 0x1786692 in main /third_party/googletest/googlemock/src/gmock_main.cc:69:10
    #18 0x7f4902d102b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)

**Comment by dneto0** [comment]
cc: @fjhenigman

**Comment by dneto0** [comment]
The object being leaked is in the DuplicateInstPass in the test fixture.  I got confused at that point.  :-)
