### ISSUE TITLE
spirv-fuzz: Null dereference in ObfuscateConstants

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#4388]
Null dereference found by ClusterFuzz: https://clusterfuzz.com/testcase-detail/4852715988254720

```
#0 0x55fc80aafcdb in spvtools::fuzz::FuzzerPassObfuscateConstants::MaybeAddConstantIdUse(spvtools::opt::Instruction const&, unsigned int, unsigned int, std::__Cr::map<SpvOp_, unsigned int, std::__Cr::less<SpvOp_>, std::__Cr::allocator<std::__Cr::pair<SpvOp_ const, unsigned int> > > const&, std::__Cr::vector<spvtools::fuzz::protobufs::IdUseDescriptor, std::__Cr::allocator<spvtools::fuzz::protobufs::IdUseDescriptor> >*) third_party/vulkan-deps/spirv-tools/src/source/opt/instruction.h:223:33
--
  | #1 0x55fc80ab0ce1 in spvtools::fuzz::FuzzerPassObfuscateConstants::Apply() third_party/vulkan-deps/spirv-tools/src/source/fuzz/fuzzer_pass_obfuscate_constants.cpp:485:13
  | #2 0x55fc809eec7d in spvtools::fuzz::Fuzzer::Run(unsigned int) third_party/vulkan-deps/spirv-tools/src/source/fuzz/fuzzer.cpp:273:9
```

**Comment by afd** [comment]
Closing as this is very likely due to MemorySanitizer leading to memory being exhausted and an allocation failing.
