### ISSUE TITLE
spirv-reduce: Null dereference in GetTargetFunctions

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#4390]
ClusterFuzz bug: https://clusterfuzz.com/testcase-detail/5157051297497088

```
#0 0x7ff7be4c1d33 in spvtools::reduce::ReductionOpportunityFinder::GetTargetFunctions(class spvtools::opt::IRContext *, unsigned int) third_party/vulkan-deps/spirv-tools/src/source/reduce/reduction_opportunity_finder.cpp:23:38
--
  | #1 0x7ff7bdf0846a in spvtools::reduce::RemoveSelectionReductionOpportunityFinder::GetAvailableOpportunities(class spvtools::opt::IRContext *, unsigned int) const third_party/vulkan-deps/spirv-tools/src/source/reduce/remove_selection_reduction_opportunity_finder.cpp:36:25
  | #2 0x7ff7bd753b94 in tint::fuzzers::spvtools_fuzzer::SpirvReduceMutator::Mutate(void) third_party/dawn/third_party/tint/fuzzers/tint_spirv_tools_fuzzer/spirv_reduce_mutator.cc:113:17
```

**Comment by afd** [comment]
Closing as this is very likely due to MemorySanitizer leading to memory being exhausted and an allocation failing.
