### ISSUE TITLE
spirv-fuzz: Null dereference in type manager arising from TransformationCompositeInsert

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#4391]
ClusterFuzz bug: https://clusterfuzz.com/testcase-detail/4791839524454400

```
#0 0x57aa6287 in spvtools::opt::analysis::Type::GetHashWords(std::__Cr::vector<unsigned int, std::__Cr::allocator<unsigned int> >*, std::__Cr::unordered_set<spvtools::opt::analysis::Type const*, std::__Cr::hash<spvtools::opt::analysis::Type const*>, std::__Cr::equal_to<spvtools::opt::analysis::Type const*>, std::__Cr::allocator<spvtools::opt::analysis::Type const*> >*) const third_party/vulkan-deps/spirv-tools/src/source/opt/types.cpp:191:20
  | #1 0x57ab4d78 in spvtools::opt::analysis::Struct::GetExtraHashWords(std::__Cr::vector<unsigned int, std::__Cr::allocator<unsigned int> >*, std::__Cr::unordered_set<spvtools::opt::analysis::Type const*, std::__Cr::hash<spvtools::opt::analysis::Type const*>, std::__Cr::equal_to<spvtools::opt::analysis::Type const*>, std::__Cr::allocator<spvtools::opt::analysis::Type const*> >*) const third_party/vulkan-deps/spirv-tools/src/source/opt/types.cpp:515:8
  | #2 0x57aa760c in spvtools::opt::analysis::Type::GetHashWords(std::__Cr::vector<unsigned int, std::__Cr::allocator<unsigned int> >*, std::__Cr::unordered_set<spvtools::opt::analysis::Type const*, std::__Cr::hash<spvtools::opt::analysis::Type const*>, std::__Cr::equal_to<spvtools::opt::analysis::Type const*>, std::__Cr::allocator<spvtools::opt::analysis::Type const*> >*) const third_party/vulkan-deps/spirv-tools/src/source/opt/types.cpp:0
  | #3 0x57aa825b in GetHashWords third_party/vulkan-deps/spirv-tools/src/source/opt/types.h:160:5
  | #4 0x57aa825b in spvtools::opt::analysis::Type::HashValue() const third_party/vulkan-deps/spirv-tools/src/source/opt/types.cpp:241:3
  | #5 0x57a9592e in operator() third_party/vulkan-deps/spirv-tools/src/source/opt/type_manager.h:47:18
  | #6 0x57a9592e in std::__Cr::pair<std::__Cr::__hash_iterator<std::__Cr::__hash_node<std::__Cr::unique_ptr<spvtools::opt::analysis::Type, std::__Cr::default_delete<spvtools::opt::analysis::Type> >, void*>*>, bool> std::__Cr::__hash_table<std::__Cr::unique_ptr<spvtools::opt::analysis::Type, std::__Cr::default_delete<spvtools::opt::analysis::Type> >, spvtools::opt::analysis::HashTypeUniquePointer, spvtools::opt::analysis::CompareTypeUniquePointers, std::__Cr::allocator<std::__Cr::unique_ptr<spvtools::opt::analysis::Type, std::__Cr::default_delete<spvtools::opt::analysis::Type> > > >::__emplace_unique_key_args<std::__Cr::unique_ptr<spvtools::opt::analysis::Type, std::__Cr::default_delete<spvtools::opt::analysis::Type> >, std::__Cr::unique_ptr<spvtools::opt::analysis::Type, std::__Cr::default_delete<spvtools::opt::analysis::Type> > >(std::__Cr::unique_ptr<spvtools::opt::analysis::Type, std::__Cr::default_delete<spvtools::opt::analysis::Type> > const&, std::__Cr::unique_ptr<spvtools::opt::analysis::Type, std::__Cr::default_delete<spvtools::opt::analysis::Type> >&&) buildtools/third_party/libc++/trunk/include/__hash_table:2072:21
  | #7 0x57a6fdf6 in __insert_unique buildtools/third_party/libc++/trunk/include/__hash_table:1129:14
  | #8 0x57a6fdf6 in insert buildtools/third_party/libc++/trunk/include/unordered_set:583:26
  | #9 0x57a6fdf6 in spvtools::opt::analysis::TypeManager::RecordIfTypeDefinition(spvtools::opt::Instruction const&) third_party/vulkan-deps/spirv-tools/src/source/opt/type_manager.cpp:883:26
  | #10 0x57a692b1 in spvtools::opt::analysis::TypeManager::AnalyzeTypes(spvtools::opt::Module const&) third_party/vulkan-deps/spirv-tools/src/source/opt/type_manager.cpp:78:5
  | #11 0x57a68ce4 in spvtools::opt::analysis::TypeManager::TypeManager(std::__Cr::function<void (spv_message_level_t, char const*, spv_position_t const&, char const*)> const&, spvtools::opt::IRContext*) third_party/vulkan-deps/spirv-tools/src/source/opt/type_manager.cpp:39:3
  | #12 0x5802b6c1 in MakeUnique<spvtools::opt::analysis::TypeManager, const std::function<void (spv_message_level_t, const char *, const spv_position_t &, const char *)> &, spvtools::opt::IRContext *> third_party/vulkan-deps/spirv-tools/src/source/util/make_unique.h:25:33
  | #13 0x5802b6c1 in BuildTypeManager third_party/vulkan-deps/spirv-tools/src/source/opt/ir_context.h:683:17
  | #14 0x5802b6c1 in get_type_mgr third_party/vulkan-deps/spirv-tools/src/source/opt/ir_context.h:326:7
  | #15 0x5802b6c1 in spvtools::fuzz::TransformationCompositeInsert::IsCompositeInstructionSupported(spvtools::opt::IRContext*, spvtools::opt::Instruction*) third_party/vulkan-deps/spirv-tools/src/source/fuzz/transformation_composite_insert.cpp:161:19
  | #16 0x57e5ae2d in operator() third_party/vulkan-deps/spirv-tools/src/source/fuzz/fuzzer_pass_add_composite_inserts.cpp:66:24
  | #17 0x57e5ae2d in __invoke<(lambda at ../../third_party/vulkan-deps/spirv-tools/src/source/fuzz/fuzzer_pass_add_composite_inserts.cpp:61:17) &, spvtools::opt::IRContext *, spvtools::opt::Instruction *> buildtools/third_party/libc++/trunk/include/type_traits:3956:1
  | #18 0x57e5ae2d in __call<(lambda at ../../third_party/vulkan-deps/spirv-tools/src/source/fuzz/fuzzer_pass_add_composite_inserts.cpp:61:17) &, spvtools::opt::IRContext *, spvtools::opt::Instruction *> buildtools/third_party/libc++/trunk/include/__functional_base:317:16
  | #19 0x57e5ae2d in operator() buildtools/third_party/libc++/trunk/include/functional:1615:12
  | #20 0x57e5ae2d in bool std::__Cr::__function::__policy_invoker<bool (spvtools::opt::IRContext*, spvtools::opt::Instruction*)>::__call_impl<std::__Cr::__function::__default_alloc_func<spvtools::fuzz::FuzzerPassAddCompositeInserts::Apply()::$_0::operator()(spvtools::opt::Function*, spvtools::opt::BasicBlock*, spvtools::opt::InstructionList::iterator, spvtools::fuzz::protobufs::InstructionDescriptor const&) const::'lambda'(spvtools::opt::IRContext*, spvtools::opt::Instruction*), bool (spvtools::opt::IRContext*, spvtools::opt::Instruction*)> >(std::__Cr::__function::__policy_storage const*, spvtools::opt::IRContext*, spvtools::opt::Instruction*) buildtools/third_party/libc++/trunk/include/functional:2096:16
  | #21 0x57e32928 in operator() buildtools/third_party/libc++/trunk/include/functional:2228:16
  | #22 0x57e32928 in operator() buildtools/third_party/libc++/trunk/include/functional:2567:12
  | #23 0x57e32928 in spvtools::fuzz::FuzzerPass::FindAvailableInstructions(spvtools::opt::Function*, spvtools::opt::BasicBlock*, spvtools::opt::InstructionList::iterator const&, std::__Cr::function<bool (spvtools::opt::IRContext*, spvtools::opt::Instruction*)>) const third_party/vulkan-deps/spirv-tools/src/source/fuzz/fuzzer_pass.cpp:66:9
  | #24 0x57e59583 in operator() third_party/vulkan-deps/spirv-tools/src/source/fuzz/fuzzer_pass_add_composite_inserts.cpp:59:13
  | #25 0x57e59583 in __invoke<(lambda at ../../third_party/vulkan-deps/spirv-tools/src/source/fuzz/fuzzer_pass_add_composite_inserts.cpp:34:7) &, spvtools::opt::Function *, spvtools::opt::BasicBlock *, spvtools::opt::InstructionList::iterator, const spvtools::fuzz::protobufs::InstructionDescriptor &> buildtools/third_party/libc++/trunk/include/type_traits:3956:1
  | #26 0x57e59583 in __call<(lambda at ../../third_party/vulkan-deps/spirv-tools/src/source/fuzz/fuzzer_pass_add_composite_inserts.cpp:34:7) &, spvtools::opt::Function *, spvtools::opt::BasicBlock *, spvtools::opt::InstructionList::iterator, const spvtools::fuzz::protobufs::InstructionDescriptor &> buildtools/third_party/libc++/trunk/include/__functional_base:348:9
  | #27 0x57e59583 in operator() buildtools/third_party/libc++/trunk/include/functional:1615:12
  | #28 0x57e59583 in void std::__Cr::__function::__policy_invoker<void (spvtools::opt::Function*, spvtools::opt::BasicBlock*, spvtools::opt::InstructionList::iterator, spvtools::fuzz::protobufs::InstructionDescriptor const&)>::__call_impl<std::__Cr::__function::__default_alloc_func<spvtools::fuzz::FuzzerPassAddCompositeInserts::Apply()::$_0, void (spvtools::opt::Function*, spvtools::opt::BasicBlock*, spvtools::opt::InstructionList::iterator, spvtools::fuzz::protobufs::InstructionDescriptor const&)> >(std::__Cr::__function::__policy_storage const*, spvtools::opt::Function*, spvtools::opt::BasicBlock*, spvtools::opt::InstructionList::iterator&&, spvtools::fuzz::protobufs::InstructionDescriptor const&) buildtools/third_party/libc++/trunk/include/functional:2096:16
  | #29 0x57e47649 in operator() buildtools/third_party/libc++/trunk/include/functional:2228:16
  | #30 0x57e47649 in operator() buildtools/third_party/libc++/trunk/include/functional:2567:12
  | #31 0x57e47649 in operator() third_party/vulkan-deps/spirv-tools/src/source/fuzz/fuzzer_pass.cpp:180:11
  | #32 0x57e47649 in __invoke<(lambda at ../../third_party/vulkan-deps/spirv-tools/src/source/fuzz/fuzzer_pass.cpp:177:9) &, spvtools::opt::BasicBlock *, spvtools::opt::InstructionList::iterator, const spvtools::fuzz::protobufs::InstructionDescriptor &> buildtools/third_party/libc++/trunk/include/type_traits:3956:1
  | #33 0x57e47649 in __call<(lambda at ../../third_party/vulkan-deps/spirv-tools/src/source/fuzz/fuzzer_pass.cpp:177:9) &, spvtools::opt::BasicBlock *, spvtools::opt::InstructionList::iterator, const spvtools::fuzz::protobufs::InstructionDescriptor &> buildtools/third_party/libc++/trunk/include/__functional_base:348:9
  | #34 0x57e47649 in operator() buildtools/third_party/libc++/trunk/include/functional:1615:12
  | #35 0x57e47649 in void std::__Cr::__function::__policy_invoker<void (spvtools::opt::BasicBlock*, spvtools::opt::InstructionList::iterator, spvtools::fuzz::protobufs::InstructionDescriptor const&)>::__call_impl<std::__Cr::__function::__default_alloc_func<spvtools::fuzz::FuzzerPass::ForEachInstructionWithInstructionDescriptor(std::__Cr::function<void (spvtools::opt::Function*, spvtools::opt::BasicBlock*, spvtools::opt::InstructionList::iterator, spvtools::fuzz::protobufs::InstructionDescriptor const&)>)::$_1, void (spvtools::opt::BasicBlock*, spvtools::opt::InstructionList::iterator, spvtools::fuzz::protobufs::InstructionDescriptor const&)> >(std::__Cr::__function::__policy_storage const*, spvtools::opt::BasicBlock*, spvtools::opt::InstructionList::iterator&&, spvtools::fuzz::protobufs::InstructionDescriptor const&) buildtools/third_party/libc++/trunk/include/functional:2096:16
  | #36 0x57e34187 in operator() buildtools/third_party/libc++/trunk/include/functional:2228:16
  | #37 0x57e34187 in operator() buildtools/third_party/libc++/trunk/include/functional:2567:12
  | #38 0x57e34187 in spvtools::fuzz::FuzzerPass::ForEachInstructionWithInstructionDescriptor(spvtools::opt::Function*, std::__Cr::function<void (spvtools::opt::BasicBlock*, spvtools::opt::InstructionList::iterator, spvtools::fuzz::protobufs::InstructionDescriptor const&)>) third_party/vulkan-deps/spirv-tools/src/source/fuzz/fuzzer_pass.cpp:154:7
  | #39 0x57e352f0 in spvtools::fuzz::FuzzerPass::ForEachInstructionWithInstructionDescriptor(std::__Cr::function<void (spvtools::opt::Function*, spvtools::opt::BasicBlock*, spvtools::opt::InstructionList::iterator, spvtools::fuzz::protobufs::InstructionDescriptor const&)>) third_party/vulkan-deps/spirv-tools/src/source/fuzz/fuzzer_pass.cpp:175:5
  | #40 0x57e5897f in spvtools::fuzz::FuzzerPassAddCompositeInserts::Apply() third_party/vulkan-deps/spirv-tools/src/source/fuzz/fuzzer_pass_add_composite_inserts.cpp:33:3
  | #41 0x57e14b32 in ApplyPassAndCheckValidity third_party/vulkan-deps/spirv-tools/src/source/fuzz/fuzzer.cpp:273:9
```

**Comment by afd** [comment]
Closing as this is very likely due to MemorySanitizer leading to memory being exhausted and an allocation failing.
