### ISSUE TITLE
Bitfields test trips assertion in optimizer

### ISSUE THREAD

**Issue by Themaister** [KhronosGroup/SPIRV-Tools#990]
```
; SPIR-V
; Version: 1.0
; Generator: Khronos Glslang Reference Front End; 1
; Bound: 47
; Schema: 0
               OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint GLCompute %main "main"
               OpExecutionMode %main LocalSize 1 1 1
               OpSource ESSL 310
               OpName %main "main"
               OpName %signed_value "signed_value"
               OpName %unsigned_value "unsigned_value"
               OpName %s "s"
               OpName %u "u"
               OpName %v0 "v0"
               OpName %v1 "v1"
               OpName %v2 "v2"
               OpName %v3 "v3"
       %void = OpTypeVoid
          %3 = OpTypeFunction %void
        %int = OpTypeInt 32 1
%_ptr_Function_int = OpTypePointer Function %int
      %int_0 = OpConstant %int 0
       %uint = OpTypeInt 32 0
%_ptr_Function_uint = OpTypePointer Function %uint
     %uint_0 = OpConstant %uint 0
      %int_5 = OpConstant %int 5
     %int_20 = OpConstant %int 20
      %int_6 = OpConstant %int 6
     %int_21 = OpConstant %int 21
     %int_40 = OpConstant %int 40
      %int_4 = OpConstant %int 4
    %uint_60 = OpConstant %uint 60
       %main = OpFunction %void None %3
          %5 = OpLabel
%signed_value = OpVariable %_ptr_Function_int Function
%unsigned_value = OpVariable %_ptr_Function_uint Function
          %s = OpVariable %_ptr_Function_int Function
          %u = OpVariable %_ptr_Function_uint Function
         %v0 = OpVariable %_ptr_Function_int Function
         %v1 = OpVariable %_ptr_Function_int Function
         %v2 = OpVariable %_ptr_Function_int Function
         %v3 = OpVariable %_ptr_Function_int Function
               OpStore %signed_value %int_0
               OpStore %unsigned_value %uint_0
         %15 = OpLoad %int %signed_value
         %18 = OpBitFieldSExtract %int %15 %int_5 %int_20
               OpStore %s %18
         %20 = OpLoad %uint %unsigned_value
         %23 = OpBitFieldUExtract %uint %20 %int_6 %int_21
               OpStore %u %23
         %24 = OpLoad %int %s
         %27 = OpBitFieldInsert %int %24 %int_40 %int_5 %int_4
               OpStore %s %27
         %28 = OpLoad %uint %u
         %30 = OpBitFieldInsert %uint %28 %uint_60 %int_5 %int_4
               OpStore %u %30
         %31 = OpLoad %uint %u
         %32 = OpBitReverse %uint %31
               OpStore %u %32
         %33 = OpLoad %int %s
         %34 = OpBitReverse %int %33
               OpStore %s %34
         %36 = OpLoad %uint %u
         %37 = OpBitCount %int %36
               OpStore %v0 %37
         %39 = OpLoad %int %s
         %40 = OpBitCount %int %39
               OpStore %v1 %40
         %42 = OpLoad %uint %u
         %43 = OpExtInst %int %1 FindUMsb %42
               OpStore %v2 %43
         %45 = OpLoad %int %s
         %46 = OpExtInst %int %1 FindILsb %45
               OpStore %v3 %46
               OpReturn
               OpFunctionEnd
```

Trips assertion when running `spirv-opt -O`
```
spirv-opt: /git/SPIRV-Tools/source/opt/instruction.h:288: const spvtools::ir::Operand& spvtools::ir::Instruction::GetOperand(uint32_t) const: Assertion `index < operands_.size() && "operand index out of bound"' failed.

(gdb) bt
#0  0x00007ffff716b8a0 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff716cf09 in abort () from /usr/lib/libc.so.6
#2  0x00007ffff71640dc in __assert_fail_base () from /usr/lib/libc.so.6
#3  0x00007ffff7164153 in __assert_fail () from /usr/lib/libc.so.6
#4  0x00005555557ccd07 in spvtools::ir::Instruction::GetOperand (this=0x555555c28ba0, index=0) at /git/SPIRV-Tools/source/opt/instruction.h:288
#5  0x00005555557ccc62 in spvtools::ir::Instruction::GetInOperand (this=0x555555c28ba0, index=0)
    at /git/SPIRV-Tools/source/opt/instruction.h:198
#6  0x000055555587aaa9 in spvtools::ir::Module::GetExtInstImportId (this=0x555555c2c780, extstr=0x555555915e2f "GLSL.std.450")
    at /git/SPIRV-Tools/source/opt/module.cpp:156
#7  0x00005555558100c3 in spvtools::opt::AggressiveDCEPass::InitCombinatorSets (this=0x555555c27260)
    at /git/SPIRV-Tools/source/opt/aggressive_dead_code_elim_pass.cpp:554
#8  0x000055555580feae in spvtools::opt::AggressiveDCEPass::ProcessImpl (this=0x555555c27260)
    at /git/SPIRV-Tools/source/opt/aggressive_dead_code_elim_pass.cpp:400
#9  0x0000555555810069 in spvtools::opt::AggressiveDCEPass::Process (this=0x555555c27260, c=0x555555c2a0f0)
    at /git/SPIRV-Tools/source/opt/aggressive_dead_code_elim_pass.cpp:411
#10 0x00005555557fce28 in spvtools::opt::Pass::Run (this=0x555555c27260, ctx=0x555555c2a0f0) at /git/SPIRV-Tools/source/opt/pass.cpp:106
#11 0x00005555557ffd0f in spvtools::opt::PassManager::Run (this=0x555555c262c8, context=0x555555c2a0f0)
    at /git/SPIRV-Tools/source/opt/pass_manager.cpp:24
#12 0x00005555557d5eb5 in spvtools::Optimizer::Run (this=0x7fffffffe458, original_binary=0x555555c29460, original_binary_size=292, 
    optimized_binary=0x7fffffffe490) at /git/SPIRV-Tools/source/opt/optimizer.cpp:113
#13 0x00005555557c702a in main (argc=5, argv=0x7fffffffe5d8) at /git/SPIRV-Tools/tools/opt/opt.cpp:480
```

**Comment by dneto0** [comment]
This no longer asserts for me.

**Comment by dneto0** [comment]
Running spirv-opt -O  I get this output:

```
               OpCapability Shader
               OpMemoryModel Logical GLSL450
               OpEntryPoint GLCompute %main "main"
               OpExecutionMode %main LocalSize 1 1 1
               OpSource ESSL 310
               OpName %main "main"
       %void = OpTypeVoid
         %12 = OpTypeFunction %void
        %int = OpTypeInt 32 1
%_ptr_Function_int = OpTypePointer Function %int
       %uint = OpTypeInt 32 0
%_ptr_Function_uint = OpTypePointer Function %uint
       %main = OpFunction %void None %12
         %26 = OpLabel
               OpReturn
               OpFunctionEnd
```
Running spirv-opt --eliminate-dead-code-aggressive I get this:
```
               OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint GLCompute %main "main"
               OpExecutionMode %main LocalSize 1 1 1
               OpSource ESSL 310
               OpName %main "main"
       %void = OpTypeVoid
         %12 = OpTypeFunction %void
        %int = OpTypeInt 32 1
%_ptr_Function_int = OpTypePointer Function %int
      %int_0 = OpConstant %int 0
       %uint = OpTypeInt 32 0
%_ptr_Function_uint = OpTypePointer Function %uint
     %uint_0 = OpConstant %uint 0
      %int_5 = OpConstant %int 5
     %int_20 = OpConstant %int 20
      %int_6 = OpConstant %int 6
     %int_21 = OpConstant %int 21
     %int_40 = OpConstant %int 40
      %int_4 = OpConstant %int 4
    %uint_60 = OpConstant %uint 60
       %main = OpFunction %void None %12
         %26 = OpLabel
               OpReturn
               OpFunctionEnd
```
